export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const DASHBOARD = '/dashboard'
export const EDITOR = '/editor'
export const APP_INFO = '/editor/appinfo'
export const LISTS = '/editor/lists'
export const FEATURES = '/editor/features'