export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const DASHBOARD = '/'
export const EDITOR = '/editor'
export const APP_INFO = '/appinfo'
export const LISTS = '/lists'
export const FEATURES = '/features'